// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tytdnhizxruknvplrzgp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InR5dGRuaGl6eHJ1a252cGxyemdwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE4MzI3NTAsImV4cCI6MjA2NzQwODc1MH0.LXeCg7S5skUXXtTyDM0zyu7YJ5iHXKb5sVdWdVazw_k";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});